site_name: Polgraw Group  

pages:
- Home: 'index.md'
- AllSky CW pipeline:
    - 'Input data generation': 'input_data.md'
    - 'Search for candidate signals': 'search_for_candidates.md'
    - 'Coincidences between candidates': 'coincidences.md'
    - 'Pipeline script': 'pipeline_script.md'
    - 'Literature': 'articles.md'

theme_dir: 'custom_theme'
markdown_extensions: ['extra', 'mathjax', 'iconfonts(base=fa,prefix=fa)']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML','js/mathjaxhelper.js']

theme: bootstrap

