site_name: Polgraw Group 

pages:
- Home: 'index.md'
- AllSky CW pipeline:
    - 'Introduction': 'polgraw-allsky/index.md'
    - 'Input data generation': 'polgraw-allsky/input_data.md'
    - 'Search for candidate signals': 'polgraw-allsky/search_for_candidates.md'
    - 'Coincidences between candidates': 'polgraw-allsky/coincidences.md'
    - 'Pipeline script': 'polgraw-allsky/pipeline_script.md'
    - 'Literature': 'polgraw-allsky/articles.md'

theme_dir: 'custom_theme'
markdown_extensions: ['extra', 'mathjax', 'iconfonts(base=fa,prefix=fa)']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML','js/mathjaxhelper.js']

theme: bootstrap

